# Generated by Django 2.2.3 on 2019-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='content',
            field=models.CharField(max_length=120),
        ),
    ]
